title: Ali Abdou Portfolio
description: Persönliches Portfolio von Ali Abdou
theme: jekyll-theme-minimal
#locale: de
languages:
  - de
  - en

exclude:
  - node_modules
  - vendor
defaults:
  - scope:
      path: ""
    values:
      layout: home
